celery_config:
    task_name: 'template'
    broker: 'sqla+sqlite:///db/celery.db'
    backend: 'db+sqlite:///db/celery.db'
    task_serializer: 'json'
    accept_content: ['json']
    result_serializer: 'json'
    timezone: 'UTC'
    enable_utc: True
    task_track_started: True
    worker_hijack_root_logger: False
    worker_concurrency: 1
    broker_connection_retry: True
    broker_connection_max_retries: None
    result_persistent: True
    worker_prefetch_multiplier: 1
    task_acks_late: True
